ALTER TABLE exam_attempts
ADD COLUMN IF NOT EXISTS access_source VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS access_entitlement_id UUID NULL,
ADD COLUMN IF NOT EXISTS access_granted_at TIMESTAMP NULL,
ADD COLUMN IF NOT EXISTS access_expires_at TIMESTAMP NULL;
